name: "Simple CI"

on:
  push:
    branches: [ main ]
   

env:
  DAGGER_LOG_FORMAT: plain
  DAGGER_CACHE_BASE: dagger-ci-build

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Git status"   
        run:  |
          pwd
          ls -la
          git status
          